import Feed from '@/components/Feed';
import Sidebar from '@/components/Sidebar'
import Widgets from '@/components/Widgets';
import Head from 'next/head'

const Home = () => {
  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen max-w-7xl mx-auto">

        {/*------------------- SideBar -------------------*/}

        <Sidebar />


        {/*------------------- Feed -------------------*/}

        <Feed />


        {/*------------------- Widgets -------------------*/}

        <Widgets />


        {/*------------------- Modal -------------------*/}

      </main>


    </>
  )
}


export default Home;